- hosts: Remora
  remote_user: root
  tasks:
    - name: clone Remora
      copy:
        src: /vagrant/Remora/Remora
        dest: /root/Remora{{item}}/
      loop:
        - 0
        - 1
        - 2
      when: (ansible_hostname is not match "node0")

    - name: clone Remora
      copy:
        src: /vagrant/Remora/Remora
        dest: /root/Remora{{item}}/
      loop:
        - 0
      when: (ansible_hostname is match "node0")

    - name: chmod Remora
      shell: chmod +x /root/Remora{{item}}/Remora
      loop:
        - 0
        - 1
        - 2
      when: (ansible_hostname is not match "node0")

    - name: chmod Remora
      shell: chmod +x /root/Remora{{item}}/Remora
      loop:
        - 0
      when: (ansible_hostname is match "node0")
