- hosts: Remora
  remote_user: vagrant
  tasks:
    - name: delete the Remora directory
      shell: rm -rf /vagrant/Remora{{item}}
      loop:
        - 0
      when: (ansible_hostname is not match "node0")

    - name: delete the Remora directory
      shell: rm -rf /vagrant/Remora{{item}}
      loop:
        - 0
      when: (ansible_hostname is match "node0")

    - name: clean the testbed directory
      shell: rm -rf /vagrant/testbed