- hosts: Remora
  remote_user: vagrant
  tasks:
    - name: create testbed dirs
      file:
        path: /vagrant/testbed
        state: directory

    - name: run Remora as a daemon
      shell: "(nohup ./Remora > /vagrant/testbed/{{inventory_hostname}}_{{item}}.txt 2>&1 &)"
      args:
        chdir: /vagrant/Remora{{item}}
      loop:
        - 0
      when: (ansible_hostname is not match "node0")

    - name: run Remora as a daemon
      shell: "(nohup ./Remora > /vagrant/testbed/{{inventory_hostname}}_{{item}}.txt 2>&1 &)"
      args:
        chdir: /vagrant/Remora{{item}}
      loop:
        - 0
      when: (ansible_hostname is match "node0")